### ISSUE TITLE
Uncaught ECONNRESET exception

### ISSUE THREAD

**Issue by Alan01252** [andrewrk/node-s3-client#120]
Hi,

We've been struggling with this today, not entirely sure why the connection was getting reset yet. I'm not entirely sure looking at the code where/how it would be best to catch this. Any help would be greatly appreciated.

Stack trace follows:

```
Error: write ECONNRESET
    at errnoException (net.js:905:11)
    at Object.afterWrite (net.js:721:19)
---------------------------------------------
    at Socket.Readable.on (_stream_readable.js:708:33)
    at pipe (tls.js:1469:10)
    at Object.exports.connect (tls.js:1366:19)
    at Agent.createConnection (https.js:79:14)
    at Agent.createSocket (http.js:1294:16)
    at Agent.addRequest (http.js:1270:23)
    at new ClientRequest (http.js:1417:16)
    at Object.exports.request (https.js:123:10)
    at [object Object].handleRequest (/srv/opt/agricameraengine/node_modules/s3/node_modules/aws-sdk/lib/http/node.js:42:23)

Thank you!

Alan
```

**Comment by faceleg** [comment]
Are you behind a proxy? 
Does setting `sslEnabled: false` e.g. https://github.com/faceleg/node-s3-client/blob/97a90cdaaf73c359ce4efb969a0f5b1166ddffd8/test/test.js#L40 help?

**Comment by Alan01252** [comment]
Thank you for your reply! :)

We're not behind a proxy, code is running on a linode and directly talking to S3. I haven't tried running without SSL and I'm not sure that's a viable option for us.

It's a really intermittent problem, we're using the library a fair bit, and it's only occasionally crashing due to this. Perhaps once every few hours.

I suspect bumping the aws-sdk library might help.

**Comment by Alan01252** [comment]
Tried using your fork with updated engine that still didn't help! Will have to dedicate to look through this next week :)

**Comment by Alan01252** [comment]
For anyone else who comes across this, we seem to of solved this problem by increasing the allowed connection pool further.

`    http.globalAgent.maxSockets = https.globalAgent.maxSockets = 100;`

Seems to be working for us now.

**Comment by faceleg** [comment]
If you would update the readme with this tip I would be forever in your debt!
