### ISSUE TITLE
Unable to upload: Error

### ISSUE THREAD

**Issue by nishvs** [andrewrk/node-s3-client#128]
Hi i am trying to upload the file using the code sample in readme but i am getting the following error

> progress 0 16384 100864
progress 0 32768 100864
progress 0 49152 100864
progress 0 65536 100864
progress 0 81920 100864
progress 0 98304 100864
progress 0 100864 100864
progress 0 100864 100864
progress 0 16384 100864
progress 0 32768 100864
progress 0 49152 100864
progress 0 65536 100864
progress 0 81920 100864
progress 0 98304 100864
progress 0 100864 100864
progress 0 100864 100864
unable to upload: Error: Non-file stream objects are not supported with SigV4 in
 AWS.S3
    at Request.computeSha256 (E:\Temp\RankingDemo\node_modules\s3\node_modules\a
ws-sdk\lib\services\s3.js:200:18)
    at Request.callListeners (E:\Temp\RankingDemo\node_modules\s3\node_modules\a
ws-sdk\lib\sequential_executor.js:97:18)
    at Request.emit (E:\Temp\RankingDemo\node_modules\s3\node_modules\aws-sdk\li
b\sequential_executor.js:77:10)
    at Request.emit (E:\Temp\RankingDemo\node_modules\s3\node_modules\aws-sdk\li
b\request.js:604:14)
    at Request.transition (E:\Temp\RankingDemo\node_modules\s3\node_modules\aws-
sdk\lib\request.js:21:12)
    at AcceptorStateMachine.runTo (E:\Temp\RankingDemo\node_modules\s3\node_modu
les\aws-sdk\lib\state_machine.js:14:12)
    at E:\Temp\RankingDemo\node_modules\s3\node_modules\aws-sdk\lib\state_machin
e.js:26:10
    at Request.<anonymous> (E:\Temp\RankingDemo\node_modules\s3\node_modules\aws
-sdk\lib\request.js:22:9)
    at Request.<anonymous> (E:\Temp\RankingDemo\node_modules\s3\node_modules\aws
-sdk\lib\request.js:606:12)
    at Request.callListeners (E:\Temp\RankingDemo\node_modules\s3\node_modules\a
ws-sdk\lib\sequential_executor.js:104:18)
    at callNextListener (E:\Temp\RankingDemo\node_modules\s3\node_modules\aws-sd
k\lib\sequential_executor.js:90:14)
    at E:\Temp\RankingDemo\node_modules\s3\node_modules\aws-sdk\lib\event_listen
ers.js:75:9
    at finish (E:\Temp\RankingDemo\node_modules\s3\node_modules\aws-sdk\lib\conf
ig.js:228:7)
    at E:\Temp\RankingDemo\node_modules\s3\node_modules\aws-sdk\lib\config.js:24
4:9
    at Credentials.get (E:\Temp\RankingDemo\node_modules\s3\node_modules\aws-sdk
\lib\credentials.js:126:7)
    at getAsyncCredentials (E:\Temp\RankingDemo\node_modules\s3\node_modules\aws
-sdk\lib\config.js:238:24)

I am using the follwing code:

app.get("/file",function(req,res){

var s3 = require('s3');

var client = s3.createClient({
    maxAsyncS3: 20,     // this is the default
    s3RetryCount: 3,    // this is the default
    s3RetryDelay: 1000, // this is the default
    multipartUploadThreshold: 20971520, // this is the default (20 MB)
    multipartUploadSize: 15728640, // this is the default (15 MB)
    s3Options: {
      accessKeyId: "xxxxxx",
      secretAccessKey: "xxxxxxxxx",
      region: "xxxxxxx",
      // endpoint: 's3.yourdomain.com',
      // sslEnabled: false
      // any other options are passed to new AWS.S3()
      // See: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#constructor-property
    },
  })

  
  var params = {
    localFile: "Uploads/LukePaulDsilva.doc",

    s3Params: {
      Bucket: "samplebucket",
      Key: "testfile",
      // other options supported by putObject, except Body and ContentLength.
      // See: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property
    },
  };
  var uploader = client.uploadFile(params);
  uploader.on('error', function(err) {
    console.error("unable to upload:", err.stack);
  });
  uploader.on('progress', function() {
    console.log("progress", uploader.progressMd5Amount,
    uploader.progressAmount, uploader.progressTotal);
  });
  uploader.on('end', function() {
    console.log("done uploading");
    res.json(200)
  });

})

**Comment by pongib** [comment]
same problem.

**Comment by socketwiz** [comment]
I also have an error trying to upload:

```
progress 0 16384 124874
progress 0 32768 124874
progress 0 49152 124874
progress 0 65536 124874
progress 0 81920 124874
progress 0 98304 124874
progress 0 114688 124874
progress 0 124874 124874
progress 0 124874 124874
progress 0 16384 124874
progress 0 32768 124874
progress 0 49152 124874
progress 0 65536 124874
progress 0 81920 124874
progress 0 98304 124874
progress 0 114688 124874
progress 0 124874 124874
progress 0 124874 124874
progress 0 16384 124874
progress 0 32768 124874
progress 0 49152 124874
progress 0 65536 124874
progress 0 81920 124874
progress 0 98304 124874
progress 0 114688 124874
progress 0 124874 124874
progress 0 124874 124874
{ [TimeoutError: Missing credentials in config]
  message: 'Missing credentials in config',
  code: 'CredentialsError',
  time: Fri Mar 18 2016 23:55:29 GMT-0400 (EDT),
  originalError:
   { message: 'Could not load credentials from any providers',
     code: 'CredentialsError',
     time: Fri Mar 18 2016 23:55:29 GMT-0400 (EDT),
     originalError:
      { message: 'Connection timed out after 1000ms',
        code: 'TimeoutError',
        time: Fri Mar 18 2016 23:55:29 GMT-0400 (EDT) } } }
```

Using this code

```javascript
                     var client = s3.createClient({
                         's3options': {
                             'acessKeyId': 'secret',
                             'secretAccessKey': 'secret',
                             'region': 'us-east-1'
                         }
                     });

                     var params = {
                         'localFile': diskPathConverted,

                         's3Params': {
                             'Bucket': 'voiceplane-media',
                             'Key': path.basename(media)
                         }
                     };

                     var uploader = client.uploadFile(params);

                     uploader.on('error', function fnError(error) {
                         console.error(error);
                     });

                     uploader.on('progress', function fnProgress() {
                         console.log('progress', uploader.progressMd5Amount,
                                     uploader.progressAmount, uploader.progressTotal);
                     });

                     uploader.on('end', function fnEnd() {
                         console.log('Converted file uploaded');
                     });
```

**Comment by socketwiz** [comment]
I figured out my problem, I had two typos:

```
s3options should be s3Options
acessKeyId should be accessKeyId
```

**Comment by fishermanswharff** [comment]
getting SigV4 error as well on `uploadDir`
```bash
unable to sync: Error: Non-file stream objects are not supported with SigV4
    at validateStreamBody (/Users/jason/Documents/Projects/apple-takehome/2-coruscant-temp-converter/node_modules/aws-sdk/lib/services/s3.js:761:17)
    at Request.disableBodySigning (/Users/jason/Documents/Projects/apple-takehome/2-coruscant-temp-converter/node_modules/aws-sdk/lib/services/s3.js:738:21)
    at Request.callListeners (/Users/jason/Documents/Projects/apple-takehome/2-coruscant-temp-converter/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/jason/Documents/Projects/apple-takehome/2-coruscant-temp-converter/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jason/Documents/Projects/apple-takehome/2-coruscant-temp-converter/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/Users/jason/Documents/Projects/apple-takehome/2-coruscant-temp-converter/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/jason/Documents/Projects/apple-takehome/2-coruscant-temp-converter/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jason/Documents/Projects/apple-takehome/2-coruscant-temp-converter/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/jason/Documents/Projects/apple-takehome/2-coruscant-temp-converter/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/jason/Documents/Projects/apple-takehome/2-coruscant-temp-converter/node_modules/aws-sdk/lib/request.js:617:12)
    at Request.callListeners (/Users/jason/Documents/Projects/apple-takehome/2-coruscant-temp-converter/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/jason/Documents/Projects/apple-takehome/2-coruscant-temp-converter/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jason/Documents/Projects/apple-takehome/2-coruscant-temp-converter/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/Users/jason/Documents/Projects/apple-takehome/2-coruscant-temp-converter/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/jason/Documents/Projects/apple-takehome/2-coruscant-temp-converter/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jason/Documents/Projects/apple-takehome/2-coruscant-temp-converter/node_modules/aws-sdk/lib/state_machine.js:26:10
```

This directory is less than 1mb, containing very simple html, css and js files (front end app). Any help would be appreciated.

**Comment by vcernomschi** [comment]
+1

**Comment by vcernomschi** [comment]
This issue is not reproducible on aws-sdk@2.3.6

**Comment by vcernomschi** [comment]
Fixed in aws-sdk@2.42. So on the latest aws-sdk it works fine.

For failed previous versions you need to v2 signature:

`var s3sdk = new aws.S3({signatureVersion: 'v2'});`

More details: https://github.com/aws/aws-sdk-js/issues/965
