### ISSUE TITLE
XMLParserError: Unexpected close tag

### ISSUE THREAD

**Issue by celicoo** [andrewrk/node-s3-client#144]
I'm trying to download files from a bucket:

```
  s3Client.downloadDir({
    localDir: '../_input',
    s3Params: {
      Bucket: 'iron-trial-3',
      Prefix: '_input/'
    }
  });
```

But it's returning: 

```
XMLParserError: Unexpected close tag
Line: 41
Column: 7
Char: >
    at error (/Users/marceloalves/DEV/Garimpo/DataExtractor/v4.0.0/node_modules/s3/node_modules/sax/lib/sax.js:352:8)
    at strictFail (/Users/marceloalves/DEV/Garimpo/DataExtractor/v4.0.0/node_modules/s3/node_modules/sax/lib/sax.js:369:22)
    at closeTag (/Users/marceloalves/DEV/Garimpo/DataExtractor/v4.0.0/node_modules/s3/node_modules/sax/lib/sax.js:531:7)
    at Object.write (/Users/marceloalves/DEV/Garimpo/DataExtractor/v4.0.0/node_modules/s3/node_modules/sax/lib/sax.js:958:29)
    at Parser.exports.Parser.Parser.parseString (/Users/marceloalves/DEV/Garimpo/DataExtractor/v4.0.0/node_modules/s3/node_modules/xml2js/lib/xml2js.js:257:29)
    at Parser.parseString (/Users/marceloalves/DEV/Garimpo/DataExtractor/v4.0.0/node_modules/s3/node_modules/xml2js/lib/xml2js.js:6:61)
    at NodeXmlParser.parse (/Users/marceloalves/DEV/Garimpo/DataExtractor/v4.0.0/node_modules/s3/node_modules/aws-sdk/lib/xml/node_parser.js:30:10)
    at Request.extractData (/Users/marceloalves/DEV/Garimpo/DataExtractor/v4.0.0/node_modules/s3/node_modules/aws-sdk/lib/protocol/rest_xml.js:78:23)
    at Request.callListeners (/Users/marceloalves/DEV/Garimpo/DataExtractor/v4.0.0/node_modules/s3/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
    at Request.emit (/Users/marceloalves/DEV/Garimpo/DataExtractor/v4.0.0/node_modules/s3/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
```

Any ideias why?

**Comment by rahulitzme94** [comment]
@celicoo probably the location you specified couldn't be accessed try providing a location which doesn't need permission. I faced a similar issue and mine was solved this way,
