### ISSUE TITLE
Webpack Error: Cannot find module './core'

### ISSUE THREAD

**Issue by kevinguard** [andrewrk/node-s3-client#156]
I am trying to get this library working but whatever hack I applied to get it working when using webpack has failed! After installation, I get the following error (although I don't think it's really helpful)

```events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module './core'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)```

**Comment by kevinguard** [comment]
A follow up question: Is this library meant to be used at client side or server side? I suspect given the aforementioned error, this needs to be used in server side.
