### ISSUE TITLE
primordials is not defined

### ISSUE THREAD

**Issue by dashritwik** [andrewrk/node-s3-client#236]
node .\s3.js  
fs.js:36
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:36:5
    at req_ (F:\troopsap\source code\test\node_modules\natives\index.js:143:24)
    at Object.req [as require] (F:\troopsap\source code\test\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (F:\troopsap\source code\test\node_modules\graceful-fs\fs.js:1:37)     
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
i'm getting this error whenever i try to run  s3

**Comment by Kopatch** [comment]
I get the same error when using node 14, I believe the issue comes from [graceful-fs](https://www.npmjs.com/package/graceful-fs) dependency, which should be updated to support newer node versions.

**Comment by abd-maqableh** [comment]
> node .\s3.js
> fs.js:36
> } = primordials;
> ^
> 
> ReferenceError: primordials is not defined
> at fs.js:36:5
> at req_ (F:\troopsap\source code\test\node_modules\natives\index.js:143:24)
> at Object.req [as require] (F:\troopsap\source code\test\node_modules\natives\index.js:55:10)
> at Object. (F:\troopsap\source code\test\node_modules\graceful-fs\fs.js:1:37)
> at Module._compile (internal/modules/cjs/loader.js:1137:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
> at Module.load (internal/modules/cjs/loader.js:985:32)
> at Function.Module._load (internal/modules/cjs/loader.js:878:14)
> at Module.require (internal/modules/cjs/loader.js:1025:19)
> at require (internal/modules/cjs/helpers.js:72:18)
> i'm getting this error whenever i try to run s3

I clone "node-graceful-fs" this package local in root project and I do this command: npm link "node-graceful-fs"
it is work with me

**Comment by pbachman** [comment]
i had the same issue with the node version 14.x, set the resolutions in package.json fixed it for me

```
 "resolutions": {
    "graceful-fs": "4.x.x"
  },
```
