### ISSUE TITLE
Error: Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by ArVan** [andrewrk/node-s3-client#64]
Hi. I'm new on integrating s3 on node. I have followed the tutorials and wrote a code for uploading files to s3. So I'm getting this error:

```
error: Server Error (500)
error: Error: Hostname/IP doesn't match certificate's altnames
    at SecurePair.<anonymous> (tls.js:1366:23)
    at SecurePair.EventEmitter.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:970:10)
    at CleartextStream.read [as _read] (tls.js:463:15)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.write [as _write] (tls.js:366:25)
    at doWrite (_stream_writable.js:219:10)
    at writeOrBuffer (_stream_writable.js:209:5)
    at EncryptedStream.Writable.write (_stream_writable.js:180:11)
    at write (_stream_readable.js:583:24)
    at flow (_stream_readable.js:592:7)
    at Socket.pipeOnReadable (_stream_readable.js:624:5) { [NetworkingError: Hostname/IP doesn't match certificate's altnames]
  message: 'Hostname/IP doesn\'t match certificate\'s altnames',
  code: 'NetworkingError',
  region: 'us-west-2',
  hostname: 's3.us-west-2.amazonaws.com',
  retryable: true,
  time: Fri Nov 21 2014 15:38:32 GMT+0400 (AMT) }
```

I'm on 'us-west-2' region and my bucket name looks like this: `photos.mysite.com`. Any suggestion?

**Comment by ianmartorell** [comment]
I had the same problem and I was missing the region code in the options object. I didn't need it in the past but for some reason I do now.
