### ISSUE TITLE
Access Denied Error

### ISSUE THREAD

**Issue by aldendaniels** [andrewrk/node-s3-client#89]
Hello, I'm trying to use `node-s3-client` to sync a directory to s3:

```javascript
    s3.createClient({
        s3Options: {
            "accessKeyId": "ACCESSKEY",
            "secretAccessKey": "SECRETKEY"
        }
    })
    .uploadDir({
        localDir: 'path/to/localdir',
        s3Params: {
            Prefix: '',
            Bucket: 'bucket-1'
        }
    });
```

I'm consistently getting an `AccessDenied` error:
```
AccessDenied: Access Denied
    at Request.extractError (/Users/alden/Source/bidder/ui/apps/onespot-dashboard/node_modules/s3/node_modules/aws-sdk/lib/services/s3.js:343:35)
    at Request.callListeners (/Users/alden/Source/bidder/ui/apps/onespot-dashboard/node_modules/s3/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
    at Request.emit (/Users/alden/Source/bidder/ui/apps/onespot-dashboard/node_modules/s3/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/alden/Source/bidder/ui/apps/onespot-dashboard/node_modules/s3/node_modules/aws-sdk/lib/request.js:604:14)
    at Request.transition (/Users/alden/Source/bidder/ui/apps/onespot-dashboard/node_modules/s3/node_modules/aws-sdk/lib/request.js:21:12)
    at AcceptorStateMachine.runTo (/Users/alden/Source/bidder/ui/apps/onespot-dashboard/node_modules/s3/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/alden/Source/bidder/ui/apps/onespot-dashboard/node_modules/s3/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/alden/Source/bidder/ui/apps/onespot-dashboard/node_modules/s3/node_modules/aws-sdk/lib/request.js:22:9)
    at Request.<anonymous> (/Users/alden/Source/bidder/ui/apps/onespot-dashboard/node_modules/s3/node_modules/aws-sdk/lib/request.js:606:12)
    at Request.callListeners (/Users/alden/Source/bidder/ui/apps/onespot-dashboard/node_modules/s3/node_modules/aws-sdk/lib/sequential_executor.js:104:18)
    at Request.emit (/Users/alden/Source/bidder/ui/apps/onespot-dashboard/node_modules/s3/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/alden/Source/bidder/ui/apps/onespot-dashboard/node_modules/s3/node_modules/aws-sdk/lib/request.js:604:14)
    at Request.transition (/Users/alden/Source/bidder/ui/apps/onespot-dashboard/node_modules/s3/node_modules/aws-sdk/lib/request.js:21:12)
    at AcceptorStateMachine.runTo (/Users/alden/Source/bidder/ui/apps/onespot-dashboard/node_modules/s3/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/alden/Source/bidder/ui/apps/onespot-dashboard/node_modules/s3/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/alden/Source/bidder/ui/apps/onespot-dashboard/node_modules/s3/node_modules/aws-sdk/lib/request.js:22:9)
```

My IAM settings are as follows:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1412975049000",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::bucket-1/*",
                "arn:aws:s3:::bucket-2/*"
            ]
        }
    ]
}
```

Any ideas as to what is going on or how to debug?
Thanks!

**Comment by aldendaniels** [comment]
Figured it out. My resources need to be 

`arn:aws:s3:::bucket-1` rather than 
`arn:aws:s3:::bucket-1/*`

Closing.

**Comment by aldendaniels** [comment]
More precisely, both permissions are needed:
```json
"Resource": [
  "arn:aws:s3:::bucket-1",
  "arn:aws:s3:::bucket-1/*",
  "arn:aws:s3:::bucket-2",
  "arn:aws:s3:::bucket-2/*"
]
```

The `/*` resource gives access to the objects within the bucket while the resource without the `/*` gives access to work with the bucket itself.

**Comment by hutch120** [comment]
This is a very old thread... but I thought I'd add some additional notes about my experience in solving this issue of `Access Denied`.

The main difference from the answer above, is that I have a multiple clients using the same bucket. I needed to allow access to their own folder.

Also note that I am using the `deleteRemoved: true` flag which appears to require `ListBucket` permissions.

The IAM policy definition that finally worked required ListBucket access to the actual bucket (as compared to the full folder path). See below for complete IAM definition.

Just as a side note, I'd avoid `s3:*` permissions used in the example above.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObjectAcl",
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "arn:aws:s3:::mybucket/client1",
                "arn:aws:s3:::mybucket/client1/*"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::mybucket"
        }
    ]
}
```
